version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - ln -s hesburgh_utilities/py hesburgh

  build:
    commands:
      - cd codebuild && hesdeploy -s dev --publishOnly # --deployBucket [bucketname]
