# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: portalResources # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
package:
  exclude:
    - "*Env"
    - "*.sh"
    - "test*"

provider:
  name: aws
  runtime: python2.7
  stackTags:
    Name: Serverless Test Harrison
    Environment: temporary
    Contact: hbeachey@nd.edu
    Owner: Harrison Beachey
    Description: Getting Serverless API Running
    InceptDate: "2017-01-19"

  environment:
    ALEPH_FUNC:
      Fn::Join:
        - ":"
        - - "arn:aws:lambda"
          - "Ref" : "AWS::Region"
          - "Ref" : "AWS::AccountId"
          - "function:portalResources-${opt:stage, self:provider.stage}-aleph"
    ILLIAD_FUNC:
      Fn::Join:
        - ":"
        - - "arn:aws:lambda"
          - "Ref" : "AWS::Region"
          - "Ref" : "AWS::AccountId"
          - "function:portalResources-${opt:stage, self:provider.stage}-illiad"

  # Can't figure out how to reference this for authorizer
  # jwtAuth:
  #   arn: { "Fn::Join": ["", ["arn:aws:lambda", { "Ref" : "AWS::Region" }, { "Ref" : "AWS::AccountId" }, "function:jwt-auth-${opt:stage, self:provider.stage}-lambda_handler"]] }

functions:
  borrowed:
    handler: joinHandler.borrowed
    timeout: 15
    events:
      - http:
          path: items/borrowed
          method: get
          headers:
            - netid
          authorizer: "arn:aws:lambda:us-east-1:333680067100:function:jwt-auth-dev-lambda_handler"

  pending:
    handler: joinHandler.pending
    timeout: 15
    events:
      - http:
          path: items/pending
          method: get
          headers:
            - netid
          authorizer: "arn:aws:lambda:us-east-1:333680067100:function:jwt-auth-dev-lambda_handler"

  aleph:
    handler: serviceHandler.aleph
    timeout: 15
    vpc:
      securityGroupIds:
        - sg-bd3e9cc1
        - sg-2e15b752
      subnetIds:
        - subnet-fee3a4d3

  illiad:
    handler: serviceHandler.illiad

