Service: gatekeeper-publish

Stacks:
  Single:
    - Name: $SERVICE-$STAGE
      Template: root.yml
      Parameters:
        OutBucket: $DEPLOY_BUCKET
        ServiceName: $SERVICE-$STAGE
        TemplateLoc: https://s3.amazonaws.com/$DEPLOY_BUCKET/$DEPLOY_FOLDER
      Tags:
        Name: $SERVICE-$STAGE
        Owner: hbeachey
        Contact: hbeachey@nd.edu
        Description: CI to publish gatekeeper files
        InceptDate: $TIMESTAMP

Artifacts:
  Templates:
    - root.yml
    - resources.yml
    - roles.yml
