AWSTemplateFormatVersion: "2010-09-09"
Description: "Resources for CI stack"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  RoleArn:
    Type: String
    Description: Arn of the Execution Role

Resources:
  DeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ServiceName
      Description: Artifact creator for gatekeeper
      ServiceRole: !Ref RoleArn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/hesutils:latest
        EnvironmentVariables:
          - Name: BUCKET
            Value: testlibnd-cf
          - Name: AWS_ROLE_ARN
            Value: true
      Source:
        Type: GITHUB
        Location: https://github.com/ndlib/gatekeeper.git
        Auth:
          Type: OAUTH
      TimeoutInMinutes: 10
