Service: gatekeeper

Stacks:
  Global:
    Tags:
      Name: $SERVICE-$STAGE
      Owner: WSE
      Contact: web-and-software-engineering-group@nd.edu
  Single:
    - Name: $SERVICE-$STAGE
      Template: root.yml
      Tags:
        Description: API to get information from aleph and illiad
      Parameters:
        ServiceName: $SERVICE-$STAGE
        Stage: $STAGE
        TemplateBucket: $DEPLOY_BUCKET
        TemplateFolder: $DEPLOY_FOLDER

Artifacts:
  Templates:
    - root.yml
    - lambdas.yml
    - gateway.yml
  Zips:
    -
      Name: code
      Files:
        - ../hesburgh/
        - ../lambdaRequests/
        - ../serviceRequests/
        - ../testdata/
        - ../alephQuery.py
        - ../joinHandler.py
        - ../serviceHandler.py

LambdaEnv:
  Global:
    KMSKey: alias/wse/kms/
  Single:
    - FunctionName: $SERVICE-$STAGE-aleph
      Environment:
        -
          Name: ALEPH_PATH
          Value: ${ALEPH_PATH}
        -
          Name: ALEPH_URL
          Value: ${ALEPH_URL}
        -
          Name: ALEPH_ITEM_PATH
          Value: ${ALEPH_ITEM_PATH}

    - FunctionName: $SERVICE-$STAGE-alephQuery
      Environment:
        -
          Name: ALEPH_PATH
          Value: ${ALEPH_PATH}
        -
          Name: ALEPH_URL
          Value: ${ALEPH_URL}
        -
          Name: ALEPH_ITEM_PATH
          Value: ${ALEPH_ITEM_PATH}

    - FunctionName: $SERVICE-$STAGE-illiad
      Environment:
        -
          Name: ILLIAD_KEY
          Value: ${ILLIAD_KEY}
        -
          Name: ILLIAD_URL
          Value: ${ILLIAD_URL}
