Service: gatekeeper

PreDeploy: preDeploy.py

Stacks:
  Global:
    Tags:
      Name: $SERVICE-$STAGE
      Owner: WSE
      Contact: web-and-software-engineering-group@nd.edu
  Single:
    - Name: $SERVICE-$STAGE
      Template: root.yml
      Tags:
        Description: API to get information from aleph and illiad
      Parameters:
        ServiceName: $SERVICE-$STAGE
        Stage: $STAGE
        TemplateBucket: $DEPLOY_BUCKET
        TemplateFolder: $DEPLOY_FOLDER
        Version: ${GIT_VERSION}
      Gateways:
        - GatewayId

Artifacts:
  Templates:
    - root.yml
    - lambdas.yml
    - gateway.yml
  Zips:
    - Name: code
      Files:
        - ../config/
        - ../hesburgh/
        - ../serviceRequests/
        - ../testdata/
        - ../lib/
        - ../alephQuery.py
        - ../serviceHandler.py
        - ../physicalAvailability.py

LambdaEnv:
  Global:
    KMSKey: alias/wse/kms/
  Single:
    - FunctionName: $SERVICE-$STAGE-aleph
      Environment:
        -
          Name: ALEPH_PATH
          Value: ${ALEPH_PATH}
        -
          Name: ALEPH_URL
          Value: ${ALEPH_URL}
        -
          Name: AUTHORIZED_CLIENTS
          Value: ${AUTHORIZED_CLIENTS}
        -
          Name: VERSION
          Value: ${GIT_VERSION}

    - FunctionName: $SERVICE-$STAGE-alephQuery
      Environment:
        -
          Name: ALEPH_PATH
          Value: ${ALEPH_PATH}
        -
          Name: ALEPH_URL
          Value: ${ALEPH_URL}
        -
          Name: ALEPH_ITEM_PATH
          Value: ${ALEPH_ITEM_PATH}
        -
          Name: AUTHORIZED_CLIENTS
          Value: ${AUTHORIZED_CLIENTS}
        -
          Name: VERSION
          Value: ${GIT_VERSION}

    - FunctionName: $SERVICE-$STAGE-alephCircHistory
      Environment:
        -
          Name: ALEPH_ORACLE_USER
          Value: ${ALEPH_ORACLE_USER}
        -
          Name: ALEPH_ORACLE_PWD
          Value: ${ALEPH_ORACLE_PWD}
        -
          Name: ALEPH_ORACLE_HOST
          Value: ${ALEPH_ORACLE_HOST}
        -
          Name: ALEPH_ORACLE_SID
          Value: ${ALEPH_ORACLE_SID}
        -
          Name: AUTHORIZED_CLIENTS
          Value: ${AUTHORIZED_CLIENTS}
        -
          Name: VERSION
          Value: ${GIT_VERSION}

    - FunctionName: $SERVICE-$STAGE-alephUserInfo
      Environment:
        -
          Name: ALEPH_ORACLE_USER
          Value: ${ALEPH_ORACLE_USER}
        -
          Name: ALEPH_ORACLE_PWD
          Value: ${ALEPH_ORACLE_PWD}
        -
          Name: ALEPH_ORACLE_HOST
          Value: ${ALEPH_ORACLE_HOST}
        -
          Name: ALEPH_ORACLE_SID
          Value: ${ALEPH_ORACLE_SID}
        -
          Name: AUTHORIZED_CLIENTS
          Value: ${AUTHORIZED_CLIENTS}
        -
          Name: VERSION
          Value: ${GIT_VERSION}

    - FunctionName: $SERVICE-$STAGE-alephRenew
      Environment:
        -
          Name: ALEPH_PATH
          Value: ${ALEPH_PATH}
        -
          Name: ALEPH_URL
          Value: ${ALEPH_URL}
        -
          Name: ALEPH_ITEM_PATH
          Value: ${ALEPH_ITEM_PATH}
        -
          Name: ALEPH_RENEW_PATH
          Value: ${ALEPH_RENEW_PATH}
        -
          Name: AUTHORIZED_CLIENTS
          Value: ${AUTHORIZED_CLIENTS}
        -
          Name: VERSION
          Value: ${GIT_VERSION}

    - FunctionName: $SERVICE-$STAGE-alephUpdate
      Environment:
        -
          Name: ALEPH_PATH
          Value: ${ALEPH_PATH}
        -
          Name: ALEPH_URL
          Value: ${ALEPH_URL}
        -
          Name: ALEPH_ITEM_PATH
          Value: ${ALEPH_ITEM_PATH}
        -
          Name: ALEPH_UPDATE_BODY
          Value: ${ALEPH_UPDATE_BODY}
        -
          Name: ALEPH_USER
          Value: ${ALEPH_USER}
        -
          Name: ALEPH_PASS
          Value: ${ALEPH_PASS}
        -
          Name: AUTHORIZED_CLIENTS
          Value: ${AUTHORIZED_CLIENTS}
        -
          Name: VERSION
          Value: ${GIT_VERSION}

    - FunctionName: $SERVICE-$STAGE-illiad
      Environment:
        -
          Name: ILLIAD_KEY
          Value: ${ILLIAD_KEY}
        -
          Name: ILLIAD_URL
          Value: ${ILLIAD_URL}
        -
          Name: AUTHORIZED_CLIENTS
          Value: ${AUTHORIZED_CLIENTS}
        -
          Name: VERSION
          Value: ${GIT_VERSION}

    - FunctionName: $SERVICE-$STAGE-primo
      Environment:
        -
          Name: PRIMO_URL
          Value: ${PRIMO_URL}
        -
          Name: PRIMO_DISPLAY_URL
          Value: ${PRIMO_DISPLAY_URL}
        -
          Name: VERSION
          Value: ${GIT_VERSION}

    - FunctionName: $SERVICE-$STAGE-location
      Environment:
        -
          Name: ALEPH_URL
          Value: ${ALEPH_URL}
        -
          Name: ALEPH_PATH
          Value: ${ALEPH_PATH}
        -
          Name: PRIMO_URL
          Value: ${PRIMO_URL}
        -
          Name: PRIMO_DISPLAY_URL
          Value: ${PRIMO_DISPLAY_URL}
        -
          Name: PRIMO_SEARCH
          Value: ${PRIMO_SEARCH}
        -
          Name: VERSION
          Value: ${GIT_VERSION}
