AWSTemplateFormatVersion: "2010-09-09"
Description: "Portal Resources Gateway"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  Stage:
    Type: String
    Description: The deployed stage
  BorrowedArn:
    Type: String
    Description: Arn for the Borrowed Lambda
  PendingArn:
    Type: String
    Description: Arn for the Pending Lambda
  AlephQueryArn:
    Type: String
    Description: Arn for the AlephQuery Lambda

Outputs:
  GatewayId:
    Value: !Ref Gateway

Resources:
  GatewayStage:
    Type: AWS::ApiGateway::Deployment
    DependsOn: Gateway
    Properties:
      RestApiId: !Ref Gateway
      StageName: !Ref Stage

  Gateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ServiceName
      Description: Get personalized library resources
      Body:
        swagger: "2.0"
        schemes:
        - "https"
        paths:
          /items/borrowed:
            get:
              responses:
                "200":
                  description: The Checked out resource information
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
                  schema:
                    $ref: '#/definitions/OutList'
                "401":
                  description: Unauthorized - most often because of invalid token
                "404":
                  description: The netid was not found
                default:
                  description: Unexpected error
                  schema:
                    $ref: '#/definitions/Error'
              security:
              - jwt: []
              x-amazon-apigateway-integration:
                uri:
                  Fn::Join:
                    - ''
                    - - "arn:aws:apigateway:"
                      - !Ref AWS::Region
                      - ":lambda:path/2015-03-31/functions/"
                      - !Ref BorrowedArn
                      - "/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
            options:
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Credentials:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Credentials: "'false'"
                      method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{statusCode:200}"
                passthroughBehavior: "when_no_match"
                type: "mock"
          /items/pending:
            get:
              responses:
                "200":
                  description: The Pending resource information
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
                  schema:
                    $ref: '#/definitions/PendList'
                "401":
                  description: Unauthorized - most often because of invalid token
                "404":
                  description: The netid was not found
                default:
                  description: Unexpected error
                  schema:
                    $ref: '#/definitions/Error'
              security:
              - jwt: []
              x-amazon-apigateway-integration:
                uri:
                  Fn::Join:
                    - ''
                    - - "arn:aws:apigateway:"
                      - !Ref AWS::Region
                      - ":lambda:path/2015-03-31/functions/"
                      - !Ref PendingArn
                      - "/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
            options:
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Credentials:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Credentials: "'false'"
                      method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{statusCode:200}"
                passthroughBehavior: "when_no_match"
                type: "mock"
          "/aleph/{systemId}":
            get:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  Fn::Join:
                    - ''
                    - - "arn:aws:apigateway:"
                      - !Ref AWS::Region
                      - ":lambda:path/2015-03-31/functions/"
                      - !Ref AlephQueryArn
                      - "/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
            options:
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Credentials:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Credentials: "'false'"
                      method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{statusCode:200}"
                passthroughBehavior: "when_no_match"
                type: "mock"
        securityDefinitions:
          jwt:
            type: "apiKey"
            name: "Authorization"
            in: "header"
            x-amazon-apigateway-authtype: "custom"
            x-amazon-apigateway-authorizer:
              authorizerUri:
                Fn::Join:
                  - ":"
                  - - arn:aws:apigateway
                    - !Ref AWS::Region
                    - lambda:path/2015-03-31/functions/arn:aws:lambda
                    - !Ref AWS::Region
                    - !Ref AWS::AccountId
                    - !Sub function:jwt-auth-${Stage}/invocations
              authorizerResultTtlInSeconds: 300
              type: "token"
        definitions:
          Item:
            type: object
            properties:
              title:
                type: string
          OutList:
            type: object
            properties:
              user:
                type: string
              checkedOut:
                type: array
                items:
                  $ref: '#/definitions/Item'
          PendList:
            type: object
            properties:
              user:
                type: string
              pending:
                type: array
                items:
                  $ref: '#/definitions/Item'
          Error:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string


