AWSTemplateFormatVersion: "2010-09-09"
Description: "Portal Resources Lambdas"

Parameters:
  Version:
    Type: String
    Description: The git version of this deployment
  ServiceName:
    Type: String
    Description: The name of the service
  RoleArn:
    Type: String
    Description: Arn of the execution role
  SourceBucket:
    Type: String
    Description: The bucket the code is in
  SourceKey:
    Type: String
    Description: The path to the code zip
  AlephSecurityGroups:
    Type: CommaDelimitedList
    Description: The security group(s) required for aleph
  AlephSubnets:
    Type: CommaDelimitedList
    Description: The subnet(s) required for aleph
  LogRetention:
    Type: Number
    Description: days
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  AlephQueryTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  AlephQueryMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 512
  AlephCircHistoryTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  AlephCircHistoryMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 256
  AlephUserInfoTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  AlephUserInfoMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 256
  AlephTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  AlephMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 512
  AlephRenewTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  AlephRenewMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 256
  AlephUpdateTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  AlephUpdateMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 256
  IlliadTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  IlliadMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 128
  PrimoTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  PrimoMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 128
  LocationTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  LocationMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 128

Outputs:
  AlephQueryArn:
    Description: AlephQuery lambda arn
    Value: !GetAtt AlephQuery.Arn
  AlephQueryLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${AlephQueryLogs}

  AlephCircHistoryArn:
    Description: AlephCircHistory lambda arn
    Value: !GetAtt AlephCircHistory.Arn
  AlephCircHistoryLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${AlephCircHistoryLogs}

  AlephUserInfoArn:
    Description: AlephUserInfo lambda arn
    Value: !GetAtt AlephUserInfo.Arn
  AlephUserInfoLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${AlephUserInfoLogs}

  AlephRenewArn:
    Description: AlephRenew lambda arn
    Value: !GetAtt AlephRenew.Arn
  AlephRenewLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${AlephRenewLogs}

  AlephArn:
    Value: !GetAtt Aleph.Arn
  AlephLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${AlephLogs}

  AlephUpdateArn:
    Description: AlephUpdate lambda arn
    Value: !GetAtt AlephUpdate.Arn
  AlephUpdateLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${AlephUpdateLogs}

  IlliadArn:
    Value: !GetAtt Illiad.Arn
  IlliadLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${IlliadLogs}

  PrimoArn:
    Value: !GetAtt Primo.Arn
  PrimoLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${PrimoLogs}

  LocationArn:
    Value: !GetAtt Location.Arn
  LocationLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${LocationLogs}

Resources:
  Aleph:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-aleph
      Description: Get aleph resources for given netid
      Runtime: python2.7
      Timeout: !Ref AlephTimeout
      MemorySize: !Ref AlephMemorySize
      Handler: serviceHandler.aleph
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
      VpcConfig:
        SecurityGroupIds: !Ref AlephSecurityGroups
        SubnetIds: !Ref AlephSubnets
  AlephPermission:
    DependsOn: Aleph
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Aleph.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  AlephLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Aleph}
      RetentionInDays: !Ref LogRetention

  AlephQuery:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-alephQuery
      Description: Query aleph for a book
      Runtime: python2.7
      Timeout: !Ref AlephQueryTimeout
      MemorySize: !Ref AlephQueryMemorySize
      Handler: alephQuery.findItem
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
      VpcConfig:
        SecurityGroupIds: !Ref AlephSecurityGroups
        SubnetIds: !Ref AlephSubnets
  AlephQueryPermission:
    DependsOn: AlephQuery
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AlephQuery.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  AlephQueryLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlephQuery}
      RetentionInDays: !Ref LogRetention

  AlephCircHistory:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-alephCircHistory
      Description: Query aleph for user's circulation history
      Runtime: python2.7
      Timeout: !Ref AlephCircHistoryTimeout
      MemorySize: !Ref AlephCircHistoryMemorySize
      Handler: alephQuery.getUserCircHistory
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
      VpcConfig:
        SecurityGroupIds: !Ref AlephSecurityGroups
        SubnetIds: !Ref AlephSubnets
  AlephCircHistoryPermission:
    DependsOn: AlephCircHistory
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AlephCircHistory.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  AlephCircHistoryLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlephCircHistory}
      RetentionInDays: !Ref LogRetention

  AlephUserInfo:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-alephUserInfo
      Description: Query aleph for info on user
      Runtime: python2.7
      Timeout: !Ref AlephUserInfoTimeout
      MemorySize: !Ref AlephUserInfoMemorySize
      Handler: alephQuery.getUserInfo
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
      VpcConfig:
        SecurityGroupIds: !Ref AlephSecurityGroups
        SubnetIds: !Ref AlephSubnets
  AlephUserInfoPermission:
    DependsOn: AlephUserInfo
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AlephUserInfo.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  AlephUserInfoLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlephUserInfo}
      RetentionInDays: !Ref LogRetention

  AlephRenew:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-alephRenew
      Description: Renew aleph item
      Runtime: python2.7
      Handler: alephQuery.renewItem
      Timeout: !Ref AlephRenewTimeout
      MemorySize: !Ref AlephRenewMemorySize
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
      VpcConfig:
        SecurityGroupIds: !Ref AlephSecurityGroups
        SubnetIds: !Ref AlephSubnets
  AlephRenewPermission:
    DependsOn: AlephRenew
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AlephRenew.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  AlephRenewLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlephRenew}
      RetentionInDays: !Ref LogRetention

  AlephUpdate:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-alephUpdate
      Description: Update aleph user
      Runtime: python2.7
      Handler: alephQuery.updateUser
      Timeout: !Ref AlephUpdateTimeout
      MemorySize: !Ref AlephUpdateMemorySize
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
      VpcConfig:
        SecurityGroupIds: !Ref AlephSecurityGroups
        SubnetIds: !Ref AlephSubnets
  AlephUpdatePermission:
    DependsOn: AlephUpdate
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AlephUpdate.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  AlephUpdateLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlephUpdate}
      RetentionInDays: !Ref LogRetention

  Illiad:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-illiad
      Description: Get illiad resources for given netid
      Runtime: python2.7
      Handler: serviceHandler.illiad
      Timeout: !Ref IlliadTimeout
      MemorySize: !Ref IlliadMemorySize
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
  IlliadPermission:
    DependsOn: Illiad
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Illiad.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  IlliadLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Illiad}
      RetentionInDays: !Ref LogRetention

  Primo:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-primo
      Description: Get primo resources for given netid
      Runtime: python2.7
      Handler: serviceHandler.primo
      Timeout: !Ref PrimoTimeout
      MemorySize: !Ref PrimoMemorySize
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
      VpcConfig:
        SecurityGroupIds: !Ref AlephSecurityGroups
        SubnetIds: !Ref AlephSubnets
  PrimoPermission:
    DependsOn: Primo
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Primo.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  PrimoLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Primo}
      RetentionInDays: !Ref LogRetention

  Location:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-location
      Description: Get location resources for given netid
      Runtime: python2.7
      Handler: physicalAvailability.handler
      Timeout: !Ref LocationTimeout
      MemorySize: !Ref LocationMemorySize
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
      VpcConfig:
        SecurityGroupIds: !Ref AlephSecurityGroups
        SubnetIds: !Ref AlephSubnets
  LocationPermission:
    DependsOn: Location
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Location.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  LocationLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Location}
      RetentionInDays: !Ref LogRetention
