AWSTemplateFormatVersion: "2010-09-09"
Description: "Portal Resources Lambdas"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  RoleArn:
    Type: String
    Description: Arn of the execution role
  SourceBucket:
    Type: String
    Description: The bucket the code is in
  SourceKey:
    Type: String
    Description: The path to the code zip
  AlephSecurityGroups:
    Type: CommaDelimitedList
    Description: The security group(s) required for aleph
  AlephSubnets:
    Type: CommaDelimitedList
    Description: The subnet(s) required for aleph
  LogRetention:
    Type: Number
    Description: days
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  BorrowedTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  BorrowedMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 128
  PendingTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  PendingMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 128
  AlephQueryTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  AlephQueryMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 512
  AlephTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  AlephMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 512
  IlliadTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  IlliadMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 128

Outputs:
  BorrowedArn:
    Description: Borrowed lambda arn
    Value: !GetAtt Borrowed.Arn

  BorrowedLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${BorrowedLogs}

  PendingArn:
    Description: Pending lambda arn
    Value: !GetAtt Pending.Arn

  PendingLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${PendingLogs}

  AlephQueryArn:
    Description: AlephQuery lambda arn
    Value: !GetAtt AlephQuery.Arn

  AlephQueryLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${AlephQueryLogs}

  AlephLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${AlephLogs}

  IlliadLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${IlliadLogs}

Resources:
  Borrowed:
    DependsOn:
      - Aleph
      - Illiad
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-borrowed
      Description: Get borrowed resources for given netid
      Runtime: python2.7
      Timeout: !Ref BorrowedTimeout
      MemorySize: !Ref BorrowedMemorySize
      Handler: joinHandler.borrowed
      Environment:
        Variables:
          ALEPH_FUNC:
            Fn::GetAtt:
              - Aleph
              - Arn
          ILLIAD_FUNC:
            Fn::GetAtt:
              - Illiad
              - Arn
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey

  BorrowedLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Borrowed}
      RetentionInDays: !Ref LogRetention

  Pending:
    Type: AWS::Lambda::Function
    DependsOn:
      - Aleph
      - Illiad
    Properties:
      FunctionName: !Sub ${ServiceName}-pending
      Description: Get pending resources for given netid
      Runtime: python2.7
      Timeout: !Ref PendingTimeout
      MemorySize: !Ref PendingMemorySize
      Handler: joinHandler.pending
      Environment:
        Variables:
          ALEPH_FUNC:
            Fn::GetAtt:
              - Aleph
              - Arn
          ILLIAD_FUNC:
            Fn::GetAtt:
              - Illiad
              - Arn
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey

  PendingLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Pending}
      RetentionInDays: !Ref LogRetention

  Aleph:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-aleph
      Description: Get aleph resources for given netid
      Runtime: python2.7
      Timeout: !Ref AlephTimeout
      MemorySize: !Ref AlephMemorySize
      Handler: serviceHandler.aleph
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
      VpcConfig:
        SecurityGroupIds: !Ref AlephSecurityGroups
        SubnetIds: !Ref AlephSubnets

  AlephLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Aleph}
      RetentionInDays: !Ref LogRetention

  AlephQuery:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-alephQuery
      Description: Query aleph for a book
      Runtime: python2.7
      Timeout: !Ref AlephQueryTimeout
      MemorySize: !Ref AlephQueryMemorySize
      Handler: alephQuery.findItem
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey
      VpcConfig:
        SecurityGroupIds: !Ref AlephSecurityGroups
        SubnetIds: !Ref AlephSubnets

  AlephQueryLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlephQuery}
      RetentionInDays: !Ref LogRetention

  Illiad:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ServiceName}-illiad
      Description: Get illiad resources for given netid
      Runtime: python2.7
      Timeout: !Ref IlliadTimeout
      MemorySize: !Ref IlliadMemorySize
      Handler: serviceHandler.illiad
      Role: !Ref RoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: !Ref SourceKey

  IlliadLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Illiad}
      RetentionInDays: !Ref LogRetention

  BorrowedPermission:
    DependsOn: Borrowed
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Borrowed.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  PendingPermission:
    DependsOn: Pending
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Pending.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  AlephQueryPermission:
    DependsOn: AlephQuery
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AlephQuery.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
