AWSTemplateFormatVersion: "2010-09-09"
Description: "Portal Resources Role"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service

Outputs:
  RoleArn:
    Description: Role for the Authorizer
    Value:
      Fn::GetAtt:
        - Role
        - Arn

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: "Allow_KMS"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                Resource: !Sub "arn:aws:kms:::alias/${ServiceName}"
