AWSTemplateFormatVersion: "2010-09-09"
Description: "Portal Resources Stack"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  Stage:
    Type: String
    Description: The deployed stage
  TemplateBucket:
    Type: String
    Description: Bucket this (and code) is deployed in
  TemplateFolder:
    Type: String
    Description: Location of template files
  AlephSecurityGroups:
    Type: String
    Description: The security group(s) required for aleph
  AlephSubnets:
    Type: String
    Description: The subnet(s) required for aleph
  AuthorizerName:
    Type: String
    Description: Name of the lambda authorizer
    Default: "jwt-auth-prod"

Outputs:
  GatewayId:
    Value: !GetAtt GatewayStack.Outputs.GatewayId

Resources:
  RolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3.amazonaws.com/${TemplateBucket}/${TemplateFolder}/roles.yml
      Parameters:
        ServiceName: !Ref ServiceName

  KeysStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesStack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3.amazonaws.com/${TemplateBucket}/${TemplateFolder}/kms.yml
      Parameters:
        ServiceName: !Ref ServiceName
        RoleArn: !GetAtt RolesStack.Outputs.RoleArn

  LambdasStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesStack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3.amazonaws.com/${TemplateBucket}/${TemplateFolder}/lambdas.yml
      Parameters:
        ServiceName: !Ref ServiceName
        SourceBucket: !Ref TemplateBucket
        SourceKey: !Sub ${TemplateFolder}/code.zip
        RoleArn: !GetAtt RolesStack.Outputs.RoleArn
        AlephSecurityGroups: !Ref AlephSecurityGroups
        AlephSubnets: !Ref AlephSubnets

  GatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdasStack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3.amazonaws.com/${TemplateBucket}/${TemplateFolder}/gateway.yml
      Parameters:
        ServiceName: !Ref ServiceName
        Stage: !Ref Stage
        BorrowedArn: !GetAtt LambdasStack.Outputs.BorrowedArn
        PendingArn: !GetAtt LambdasStack.Outputs.PendingArn
        AlephQueryArn: !GetAtt LambdasStack.Outputs.AlephQueryArn
        AlephRenewArn: !GetAtt LambdasStack.Outputs.AlephRenewArn
        AuthorizerName: !Ref AuthorizerName
