AWSTemplateFormatVersion: "2010-09-09"
Description: "Portal Resources Stack"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  Stage:
    Type: String
    Description: The deployed stage
  TemplateBucket:
    Type: String
    Description: Bucket this (and code) is deployed in
  TemplateFolder:
    Type: String
    Description: Location of template files
  AlephSecurityGroups:
    Type: String
    Description: The security group(s) required for aleph
  AlephSubnets:
    Type: String
    Description: The subnet(s) required for aleph
  AuthorizerName:
    Type: String
    Description: Name of the lambda authorizer
    Default: "jwt-auth-prod"
  Version:
    Type: String
    Description: The git verison of this deployment

Outputs:
  GatewayId:
    Value: !GetAtt GatewayStack.Outputs.GatewayId

Resources:
  LambdasStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3.amazonaws.com/${TemplateBucket}/${TemplateFolder}/lambdas.yml
      Parameters:
        ServiceName: !Ref ServiceName
        SourceBucket: !Ref TemplateBucket
        SourceKey: !Sub ${TemplateFolder}/code.zip
        RoleArn: !ImportValue LambdaVPCServiceRole
        AlephSecurityGroups: !Ref AlephSecurityGroups
        AlephSubnets: !Ref AlephSubnets
        Version: !Ref Version

  GatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdasStack
    Properties:
      TemplateURL:
        Fn::Sub: https://s3.amazonaws.com/${TemplateBucket}/${TemplateFolder}/gateway.yml
      Parameters:
        ServiceName: !Ref ServiceName
        Stage: !Ref Stage
        AlephArn: !GetAtt LambdasStack.Outputs.AlephArn
        IlliadArn: !GetAtt LambdasStack.Outputs.IlliadArn
        PrimoArn: !GetAtt LambdasStack.Outputs.PrimoArn
        AlephQueryArn: !GetAtt LambdasStack.Outputs.AlephQueryArn
        AlephRenewArn: !GetAtt LambdasStack.Outputs.AlephRenewArn
        AlephUpdateArn: !GetAtt LambdasStack.Outputs.AlephUpdateArn
        LocationArn: !GetAtt LambdasStack.Outputs.LocationArn
        AuthorizerName: !Ref AuthorizerName
