swagger: '2.0'
info:
  title: Portal Resources
  description: Get library resource information for a user
  version: "1.0.0"

# the domain of the service
schemes:
  - https
paths:
  /aleph/{systemId}:
    get:
      summary: Get information about an aleph item by system number
      parameters:
        - in: path
          name: systemId
          type: integer
          required: true
          description: The system number
      responses:
        200:
          description: Aleph data
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
          schema:
            $ref: '#/definitions/AlephInfo'
        404:
          description: The item was not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

securityDefinitions:
  jwt:
    type: "apiKey"
    name: "Authorization"
    in: "header"

definitions:
  AlephInfo:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      purl:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
